
# when using the default proxy server port
# * for devolopment

# local_backend: true

# backend:
#   name: local

# * for devolopment

# * for Production

backend:
  name: github
  repo: sanabel-al-firdaws/sanabel-al-firdaws.github.io
  branch: main
  base_url: https://sveltia-cms-auth.abdullhakim-sami.workers.dev

# * for Production

collections:

  - label: باب الإسلام
    name: al-islam
    create: true
  
    fields:
      - label: محتوى المقال
        name: body
        widget: markdown
      - label: عنوان المقال
        name: title
        widget: string

      - label: رابط المقال
        name: filename
        widget: string
      
      # - label: العلامات
      #   name: tags
      #   required: false
      #   widget: list

    # path: "{{slug}}"
    slug: "{{fields.filename}}"
    extension: mdoc
    format: frontmatter
    folder: /src/content/docs/ar/aqida/al-islam
    # path: '/aqida/al-ehsan/{{fields.path}}.{{extension}}'


    # nested:
    #   depth: 100 # max depth to show in the collection tree
  - label: باب الإيمان
    name: al-eman
    create: true
  
    fields:
      - label: محتوى المقال
        name: body
        widget: markdown
      - label: عنوان المقال
        name: title
        widget: string

      - label: رابط المقال
        name: filename
        widget: string
      
      # - label: العلامات
      #   name: tags
      #   required: false
      #   widget: list

    # path: "{{slug}}"
    slug: "{{fields.filename}}"
    extension: mdoc
    format: frontmatter
    folder: src/content/docs/ar/aqida/al-eman
    # path: '/aqida/al-ehsan/{{fields.path}}.{{extension}}'


    # nested:
    #   depth: 100 # max depth to show in the collection tree
  - label: باب الإحسان
    name: al-ehsan
    create: true
  
    fields:
      - label: محتوى المقال
        name: body
        widget: markdown
      - label: عنوان المقال
        name: title
        widget: string

      - label: رابط المقال
        name: filename
        widget: string
      
      # - label: العلامات
      #   name: tags
      #   required: false
      #   widget: list

    # path: "{{slug}}"
    slug: "{{fields.filename}}"
    extension: mdoc
    format: frontmatter
    folder: src/content/docs/ar/aqida/al-ehsan
    # path: '/aqida/al-ehsan/{{fields.path}}.{{extension}}'


    # nested:
    #   depth: 100 # max depth to show in the collection tree

  - label: Al-Islam Chapter
    name: al-islam-en
    create: true
  
    fields:
      - label: محتوى المقال
        name: body
        widget: markdown
      - label: عنوان المقال
        name: title
        widget: string

      - label: رابط المقال
        name: filename
        widget: string
      
      # - label: العلامات
      #   name: tags
      #   required: false
      #   widget: list

    # path: "{{slug}}"
    slug: "{{fields.filename}}"
    extension: mdoc
    format: frontmatter
    folder: src/content/docs/en/aqida/al-islam
    # path: '/aqida/al-ehsan/{{fields.path}}.{{extension}}'


    # nested:
    #   depth: 100 # max depth to show in the collection tree
  - label: Al-Eman Chapter
    name: al-eman-en
    create: true
  
    fields:
      - label: محتوى المقال
        name: body
        widget: markdown
      - label: عنوان المقال
        name: title
        widget: string

      - label: رابط المقال
        name: filename
        widget: string
      
      # - label: العلامات
      #   name: tags
      #   required: false
      #   widget: list

    # path: "{{slug}}"
    slug: "{{fields.filename}}"
    extension: mdoc
    format: frontmatter
    folder: src/content/docs/en/aqida/al-eman
    # path: '/aqida/al-ehsan/{{fields.path}}.{{extension}}'


    # nested:
    #   depth: 100 # max depth to show in the collection tree
  - label: Al-Ehsan Chapter
    name: al-ehsan-en
    create: true
  
    fields:
      - label: محتوى المقال
        name: body
        widget: markdown
      - label: عنوان المقال
        name: title
        widget: string

      - label: رابط المقال
        name: filename
        widget: string
      
      # - label: العلامات
      #   name: tags
      #   required: false
      #   widget: list

    # path: "{{slug}}"
    slug: "{{fields.filename}}"
    extension: mdoc
    format: frontmatter
    folder: src/content/docs/en/aqida/al-ehsan
    # path: '/aqida/al-ehsan/{{fields.path}}.{{extension}}'


    # nested:
    #   depth: 100 # max depth to show in the collection tree

disable_local_backup: false

site_url: https://sanabel-al-firdaws.github.io/

logo_url : /favicon.svg
media_folder: public/img

## todo change slug and path to allow you to use i18n features
 
 
